services:
  nodebackend:
    build:
      context: ./node-js
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - ai-backend
    networks:
      - app-network

  ai-backend:
    build:
      context: ./python-ai
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
